url: "https://vrton.org"
baseurl: ""
safe: false
whitelist:
  - jekyll-polyglot
lang: "en"
languages: ["en", "es"]
default_lang: "en"
parallel_localization: false
exclude_from_localization:
  - _site
  - site.webmanifest
  - robots.txt
  - styles.css
  - script.js

title: "VRTon"
tagline: "Using Technology to Change Lives"
description: "VRTon is a voluntary initiative bringing together VR communities to achieve charitable goals through virtual reality events."
logo: "/assets/logo.png"

author:
  name: "VRTon"

social:
  name: "VRTon"
  links:
    - "https://discord.gg/AR72D2nfpp"
    - "https://www.instagram.com/vrtonof/"
    - "https://x.com/vrtonof"
    - "https://www.tiktok.com/@vrtonoficial"
    - "https://www.youtube.com/@VRTonOficial"
    - "https://www.twitch.tv/vrtonof"

twitter:
  username: "vrtonof"
  card: summary_large_image

plugins:
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

jekyll-minifier:
  compress_css: true
  compress_javascript: true
  uglifier_args:
    harmony: true
  compress_html: true
  remove_comments: true

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - .dockerignore
  - node_modules/
  - vendor/
  - .bundle
  - .github/
